### ISSUE TITLE
Problem authenticating StilleBot for Emote Checklist

### ISSUE THREAD

**Issue by Infinitay** [Rosuav/StilleBot#1]
I've been using your emote checklist for a while now, thank you for making it, but for the past few weeks I've been having issues with using it due to authentication. Whenever I click on the log in button to authenticate StilleBot, the first authorization seems to go through because it gets listed on my [Twitch Connections](https://www.twitch.tv/settings/connections). However, for some reason I get redirected to a page saying something went wrong and to try again with the following message:

> Hey, sorry, something seems to be messed up. Rosuav is looking into it. For now, you may be able to get logged in by clicking this button:

I'm a bit weary of authorizing it on the second request for two reasons:
1. The bot seems to be already authorized and connected as it's listed under my Twitch Connections
2. It's asking for more _intrusive_ permissions (side note, it seems like you're accidentally requesting these same scopes twice)
 - chat:edit
 - chat:login (deprecated)

I would appreciate any assistance, thank you

**Comment by Rosuav** [comment]
Is "Infinitay" your Twitch username? I could look into this in more detail.

**Comment by Infinitay** [comment]
`callmeinfinity` Thank you

**Comment by Rosuav** [comment]
I think it may be a consequence of, as you noted, the legacy permissions. Twitch has had OAuth for a very long time, and some things have been there for quite a while, and sometimes things get into weird states. I've tried to manually clear your authentication, which should mean you need to log in fresh next time; that hopefully should fix things.

**Comment by Rosuav** [comment]
BTW, being listed in "Twitch Connections" doesn't mean that the bot is allowed to view your emotes, which is necessary for that checklist. So my guess is that the first one didn't fully succeed, it just partly did.

**Comment by Infinitay** [comment]
> I think it may be a consequence of, as you noted, the legacy permissions. Twitch has had OAuth for a very long time, and some things have been there for quite a while, and sometimes things get into weird states. I've tried to manually clear your authentication, which should mean you need to log in fresh next time; that hopefully should fix things.

That seems to have done the trick. Thanks for the help

> being listed in "Twitch Connections" doesn't mean that the bot is allowed to view your emotes, which is necessary for that checklist
TIL I was under the assumption that if it gets listed it means a successful connection was established

**Comment by Rosuav** [comment]
Good to hear, thanks! If anyone else is having trouble like this, you may be able to fix it by logging out and in again, but if not (and if this becomes a regular thing), I may need to make a proper "clear all auth" action.

> TIL I was under the assumption that if it gets listed it means a successful connection was established

It does, but the connection is always limited/restricted. That's one of the beauties of OAuth, as used by Twitch and many other services: you can grant precisely the permissions you want, and no others. You can see a bunch of different options here: https://mustardmine.com/twitchlogin Some of them are fairly benign (eg "see hype train status", or "view chat messages as they happen"), others are much more drastic ("see your stream key and stream on your behalf"), but even if not a single checkbox is selected, you would get a connection - and that can be used for certain very minor things, like knowing your user ID and display name. That's going to be enough to show up as a "successful connection".

**Comment by Infinitay** [comment]
> you may be able to fix it by logging out and in again

You brought something to my attention. Recently I deactivated my Twitch account before returning back to Twitch. It expired all of my prior authorizations and tokens. I guess that's where things went wrong here when I tried to re-auth afterwards?

**Comment by Rosuav** [comment]
Ah, that's definitely possible. The bot might have retained some previous record, but Twitch said "hey, no, you don't have that permission", and required the reauth. This can definitely result in some confusions.
