### ISSUE TITLE
Emote Checklist: Missing Special emotes

### ISSUE THREAD

**Issue by Infinitay** [Rosuav/StilleBot#2]
I noticed some emotes missing from the emote checklist and would like to ask to see if you care enough to add them on your page?

```txt
// Key = Emote Name and Value == Emote Set ID
┌───────────────────┬─────────────────┬────────────────────────────────────────┐
│ (iteration index) │ Key             │ Values                                 │
├───────────────────┼─────────────────┼────────────────────────────────────────┤
│ 0                 │ 'LightsSwirl'   │ 'ff12b988-d6da-4f86-a701-39ffa17c778c' │
│ 1                 │ 'SSSsssplode'   │ '560c6a32-134b-4340-8185-a3e99e87237b' │
│ 2                 │ 'LightsBlink'   │ 'ff12b988-d6da-4f86-a701-39ffa17c778c' │
│ 3                 │ 'TreatCorn'     │ '24cee50f-5dc5-4ec5-93cd-5a2ebb004e62' │
│ 4                 │ 'LightsTwinkle' │ 'ff12b988-d6da-4f86-a701-39ffa17c778c' │
│ 5                 │ 'TrickCorn'     │ '24cee50f-5dc5-4ec5-93cd-5a2ebb004e62' │
└───────────────────┴─────────────────┴────────────────────────────────────────┘
```

Fetched it from the current emotes added to the `qa_tw_partner` channel (139075904). From there, I filtered out to see if they were updated to the latest emote id and with the type `limitedtime` because I assume this is where most of the new special emotes are. At least, the few that immediately come to mind which aren't global.

JS snippet where `data` is the response object for the API call to `/helix/chat/emotes`:
`Array.from(data.data).filter(emote => !(+emote.emote_set_id) && emote.emote_type === "limitedtime").forEach(emote => map2.set(emote.name, emote.emote_set_id));`
- `!(+emote.emote_set_id)` rudimentary filtered to see if the `emote_set_id` of an emote object **is not a number type**. So something like `emotesv2` would pass
- `emote.emote_type === "limitedtime"` filtered to see if the `emote_type ` of an emote object is a limited time emote rather than a permanent or temporary (global) emote
	- This emote type also matches old hype train emotes, so that's why I'm also filtered to make sure the emote_set_id is the _new_ id format

- `LightsSwirl`, `LightsBlink`, and `LightsTwinkle` are for the current "[Twitch Holiday Hoopla](https://blog.twitch.tv/en/2024/12/02/twitch-holiday-hoopla/)" event for December 2024.
	- This is a guess since I'm not sure if these are this events emotes, but I reckon so?
- `TreatCorn` and `TrickCorn` are from the "[Twitch Fright Fest](https://blog.twitch.tv/en/2024/10/17/twitch-fright-fest/)" event during October 2024
	- I know this for a fact because it was also listed in a tweet, but truthfully I'm too lazy to dig up for that tweet
	- TrickCorn was handed out if you streamed in shared chat I believe
	- TreatCorn was handed out to anyone if you watched the certain tag (and a shared chat?)
- `SSSsssplode` seems to be from [Minecraft's 15th anniversary event on Twitch](https://blog.twitch.tv/en/2024/05/15/celebrating-15-years-of-minecraft-on-twitch/) during May 2024

**Comment by Rosuav** [comment]
I can certainly add those, and thanks for grabbing their IDs. What category do they belong in, and do you know WHAT limited time they were/are available from?

**Comment by Infinitay** [comment]
Thank you and no problem. I just finished updating the OP with details on the events where you could obtain them. 

> What category do they belong in

I would argue that they should go under the "[Special](https://github.com/Rosuav/StilleBot/blob/45ba8b159309a22bc0b3f107a67e3049e51b04b4/modules/http/checklist.pike#L120)" category since there are only a few at a time per event or requires specific tasks to unlock them

**Comment by Rosuav** [comment]
Hmm. The UUIDs you give don't seem to be the same as the ones in the emotes' URIs. I'm trying to recreate the API call you did, but /helix/chat/emotes expects a broadcaster ID and only gives emotes for that broadcaster. Did you mean /helix/chat/emotes/user ? If so, I won't be able to get the same info you did, since I don't myself have those emotes (other than TreatCorn).

**Comment by Infinitay** [comment]
> Hmm. The UUIDs you give don't seem to be the same as the ones in the emotes' URIs. I'm trying to recreate the API call you did, but /helix/chat/emotes expects a broadcaster ID and only gives emotes for that broadcaster. Did you mean /helix/chat/emotes/user ? If so, I won't be able to get the same info you did, since I don't myself have those emotes (other than TreatCorn).

I was just describing how I fetched all the existing emotes `/helix/chat/emotes?broadcaster_id=139075904`. If you'd like the data for the emotes within the set, then you can do `/helix/chat/emotes/set?emote_set_id=ff12b988-d6da-4f86-a701-39ffa17c778c` and verify if there are any other emotes in those respective sets.

However, if you just need the data, then here you are:

<details><summary>Emote Data for the 6 previously mentioned emotes</summary>
<p>

```json
[
  {
    "id": "emotesv2_beda979b077141acaa5fb0196e52a544",
    "name": "LightsSwirl",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_beda979b077141acaa5fb0196e52a544/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_beda979b077141acaa5fb0196e52a544/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_beda979b077141acaa5fb0196e52a544/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "ff12b988-d6da-4f86-a701-39ffa17c778c",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  },
  {
    "id": "emotesv2_df1b3a19d9fc4bff81429afdfb46fff0",
    "name": "SSSsssplode",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_df1b3a19d9fc4bff81429afdfb46fff0/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_df1b3a19d9fc4bff81429afdfb46fff0/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_df1b3a19d9fc4bff81429afdfb46fff0/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "560c6a32-134b-4340-8185-a3e99e87237b",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  },
  {
    "id": "emotesv2_f1337249b2ac4482ad1a9318bf2018f2",
    "name": "LightsBlink",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_f1337249b2ac4482ad1a9318bf2018f2/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_f1337249b2ac4482ad1a9318bf2018f2/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_f1337249b2ac4482ad1a9318bf2018f2/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "ff12b988-d6da-4f86-a701-39ffa17c778c",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  },
  {
    "id": "emotesv2_0672054d322f4bd7a176b905b612810b",
    "name": "TreatCorn",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_0672054d322f4bd7a176b905b612810b/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_0672054d322f4bd7a176b905b612810b/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_0672054d322f4bd7a176b905b612810b/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "24cee50f-5dc5-4ec5-93cd-5a2ebb004e62",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  },
  {
    "id": "emotesv2_2d3b718f2de34770ba2e61cfbc270a58",
    "name": "LightsTwinkle",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_2d3b718f2de34770ba2e61cfbc270a58/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_2d3b718f2de34770ba2e61cfbc270a58/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_2d3b718f2de34770ba2e61cfbc270a58/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "ff12b988-d6da-4f86-a701-39ffa17c778c",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  },
  {
    "id": "emotesv2_e1623767957941d3960a16bab644b53e",
    "name": "TrickCorn",
    "images": {
      "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_e1623767957941d3960a16bab644b53e/static/light/1.0",
      "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_e1623767957941d3960a16bab644b53e/static/light/2.0",
      "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_e1623767957941d3960a16bab644b53e/static/light/3.0"
    },
    "tier": "",
    "emote_type": "limitedtime",
    "emote_set_id": "24cee50f-5dc5-4ec5-93cd-5a2ebb004e62",
    "format": ["static", "animated"],
    "scale": ["1.0", "2.0", "3.0"],
    "theme_mode": ["light", "dark"]
  }
]
```

</p>
</details>

**Comment by Rosuav** [comment]
> I was just describing how I fetched all the existing emotes `/helix/chat/emotes?broadcaster_id=139075904`

Ohhhh I understand now, thanks.

I decided to give these their own section up above, in case there's something like this again next year. The emotes you listed have now been added to the checklist. Thank you for helping with this research, I really appreciate it!

**Comment by Infinitay** [comment]
Thanks for taking the time to implement it

**Comment by Infinitay** [comment]
@Rosuav Turns out Twitch added another emote recently to the December 2024 Holidays category:

```json
{
      "id": "emotesv2_a7768ce4552c4a3abdd0404f556f958e",
      "name": "CatintheChat",
      "images": {
        "url_1x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_a7768ce4552c4a3abdd0404f556f958e/static/light/1.0",
        "url_2x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_a7768ce4552c4a3abdd0404f556f958e/static/light/2.0",
        "url_4x": "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_a7768ce4552c4a3abdd0404f556f958e/static/light/3.0"
      },
      "tier": "",
      "emote_type": "limitedtime",
      "emote_set_id": "ff12b988-d6da-4f86-a701-39ffa17c778c",
      "format": [
        "static"
      ],
      "scale": [
        "1.0",
        "2.0",
        "3.0"
      ],
      "theme_mode": [
        "light",
        "dark"
      ]
    }
    ```
    
    Would you kindly add this to the list? Thank you.

**Comment by Rosuav** [comment]
Done!

**Comment by Infinitay** [comment]
Thanks again
